version: '3.8'

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
      - ./data:/app/data
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_TOKEN=""  # Empty token for easier access
      - JUPYTER_CONFIG_DIR=/app/.jupyter
    networks:
      - hotel-tracker
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
    command: >
      bash -c "
        mkdir -p /app/.jupyter &&
        echo 'c.ServerApp.terminado_settings={\"shell_command\": [\"/bin/bash\"]}' > /app/.jupyter/jupyter_server_config.py &&
        jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''"


  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - hotel-tracker
  #   depends_on:
  #     - scraper

networks:
  hotel-tracker:
    driver: bridge
